server:
  port: 88


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: https://gitee.com    #匹配后提供服务的路由地址
          predicates:
            - Query=url,baidu   #断言,路径相匹配的进行路由
        - id: payment_routh2
          uri: lb://gulimall-coupon
          predicates:
            - Path=/coupon/coupon/**   #断言,路径相匹配的进行路由
        - id: product_router
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}

        - id: thirdparty_router
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/?(?<segment>.*), /$\{segment}

        - id: admin_router
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}
