spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  mvc:
    static-path-pattern: /static/**

  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 13000
  servlet:
    session:
      timeout: 30


